spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/we-marvel
    username: postgres
    password: 123

  sql:
    init:
      platform: postgres
      mode: always

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
    open-in-view: false

  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 50MB

logging:
  level:
    org.hibernate.sql: DEBUG
    org.hibernate.type.org.hibernate.type.descriptor.sql.BasicBinder: DEBUG

server:
  port: 6600

security:
  firebase-props:
    database-url: ${FIREBASE_DATABASE}
    enable-strict-server-session: false
    enable-check-session-revoked: false
    enable-logout-everywhere: false
    session-expiry-in-days: 5
  allow-credentials: true
  allowed-origins:
    - https://${DOMAIN}
    - http://localhost:8080
  allowed-methods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
    - OPTIONS
  allowed-headers:
    - Authorization
    - Origin
    - Content-Type
    - Accept
    - Accept-Encoding
    - Accept-Language
    - Access-Control-Allow-Origin
    - Access-Control-Allow-Headers
    - Access-Control-Request-Method
    - X-Requested-With
    - X-Auth-Token
    - X-Xsrf-Token
    - Cache-Control
    - Id-Token
  allowed-public-apis:
    - /favicon.ico
    - /session/login
    - /public/**
    - /user
    - /user/{username}
    - /user/profile
    - /character/**
    - /comic/**
    - /series/**
    - /forum/boards
    - /forum/topic/{topicId}
    - /forum/topic/{topicId}/name
    - /forum/board/{boardId}/name
    - /forum/board/{boardId}
    - /forum/character/{characterId}/topic
    - /forum/comic/{comicId}/topic
    - /forum/series/{seriesId}/topic
    - /forum/board/{boardId}/topic/{topicId}/post/image
    - /comicProgress/shared
    - /comicProgress/unique
    - /comicProgress/user/{username}
    - /comicProgress/user/{username}/comic/{comicId}
    - /friend/{username}/accepted
    - /review
    - /review/user/{username}
    - /review/{entityId}
    - /review/character/{id}
    - /review/comic/{id}
    - /review/series/{id}
  exposed-headers:
    - X-Xsrf-Token